-- ==============================================================================
-- RuangSela MVP Final Database Schema
-- Focus: Early Academic Stress Detection, Journaling, & Support Referrals.
-- ==============================================================================

-- Trigger to automatically update the 'updated_at' column
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = EXECUTED_AT;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 1. PROFILES
-- Stores basic user information linked to Supabase Auth.
CREATE TABLE public.profiles (
  id uuid REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  full_name text NOT NULL,
  university text NOT NULL,
  faculty text,
  major text,
  semester integer,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TRIGGER update_profiles_modtime BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- 2. STRESS ONBOARDING
-- Baseline static data identifying the student's structural academic load.
CREATE TABLE public.stress_onboarding (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  sks_count integer NOT NULL,
  org_involvement text NOT NULL,
  sleep_hours numeric,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(user_id) -- One onboarding per user
);

CREATE TRIGGER update_onboarding_modtime BEFORE UPDATE ON public.stress_onboarding FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- 3. STRESS CHECKINS
-- Weekly dynamic inputs where students report acute feelings of pressure.
CREATE TABLE public.stress_checkins (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  deadlines_count integer NOT NULL,
  exams_count integer NOT NULL,
  exhaustion_level integer CHECK (exhaustion_level BETWEEN 1 AND 10),
  academic_pressure integer CHECK (academic_pressure BETWEEN 1 AND 10),
  emotional_overwhelm integer CHECK (emotional_overwhelm BETWEEN 1 AND 10),
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. STRESS RESULTS
-- The calculated insight matching a specific check-in with the onboarding baseline.
CREATE TABLE public.stress_results (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  checkin_id uuid REFERENCES public.stress_checkins(id) ON DELETE CASCADE,
  score numeric NOT NULL,
  level text CHECK (level IN ('Aman', 'Waspada', 'Tinggi')) NOT NULL,
  overload_indicator boolean DEFAULT false NOT NULL,
  burnout_risk boolean DEFAULT false NOT NULL,
  assessed_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. JOURNALS
-- Freeform text generated by the user detailing their emotional state.
CREATE TABLE public.journals (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  content text NOT NULL CHECK (char_length(content) >= 10),
  mood text NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TRIGGER update_journals_modtime BEFORE UPDATE ON public.journals FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- 6. AI INSIGHTS
-- Structured JSON outputs from the LLM tied 1:1 with a Journal entry.
CREATE TABLE public.ai_insights (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  journal_id uuid REFERENCES public.journals(id) ON DELETE CASCADE NOT NULL,
  summary text NOT NULL,
  emotions jsonb NOT NULL,
  triggers jsonb NOT NULL,
  coping_suggestions jsonb NOT NULL,
  next_step text NOT NULL,
  concerning_signs boolean DEFAULT false NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(journal_id)
);

-- 7. TRUSTED BUDDIES
-- Safety contacts explicitly managed by the student.
CREATE TABLE public.trusted_buddies (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  buddy_name text NOT NULL,
  relationship text NOT NULL,
  phone_number text NOT NULL,
  notes text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TRIGGER update_buddies_modtime BEFORE UPDATE ON public.trusted_buddies FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- 8. HELP REQUESTS
-- Formal outreach logs requesting intervention from the campus or partner.
CREATE TABLE public.help_requests (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  issue_category text NOT NULL,
  description text NOT NULL,
  urgency_level text CHECK (urgency_level IN ('Rendah', 'Sedang', 'Tinggi')) NOT NULL,
  preferred_support text NOT NULL,
  status text DEFAULT 'Menunggu' CHECK (status IN ('Menunggu', 'Diproses', 'Selesai')) NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TRIGGER update_requests_modtime BEFORE UPDATE ON public.help_requests FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ==============================================================================
-- RECOMMENDED INDEXES FOR SCALABILITY
-- ==============================================================================
CREATE INDEX idx_stress_results_user_at ON public.stress_results (user_id, assessed_at DESC);
CREATE INDEX idx_journals_user_created ON public.journals (user_id, created_at DESC);
CREATE INDEX idx_insights_concerning ON public.ai_insights (concerning_signs) WHERE concerning_signs = true;
CREATE INDEX idx_help_status ON public.help_requests (status, created_at ASC);
